name: 'Publish tag manager'
description: 'Extracts semver version and publish tag from github tag or package.json'
author: 'Yuki'
inputs:
  prefix:
    description: 'Prefix to strip from tag (e.g. v, release-'
    required: false
    default: 'v'
  source:
    description: |
      Optional path to a package.json file to read version from.
      - If provided: version will be read from this file, and the prefix will be ignored.
      - If omitted: version will be parsed from Git tag (e.g. refs/tags/v1.2.3)
    required: false
    default: ''
outputs:
  tag:
    description: "NPM publish tag (e.g. latest, beta)"
  full:
    description: "Semantic version and build"
  version:
    description: "Full semantic version (e.g. 1.2.3-beta.1)"
  major:
    description: "Major version number"
  minor:
    description: "Minor version number"
  patch:
    description: "Patch version number"
  build:
    description: "Build version number"
runs:
  using: node20
  main: ./dist/index.cjs
branding:
  icon: "tag"
  color: "green"