name: Release and Publish

on:
  push:
    branches:
      - main

jobs:
  release:
    if: startsWith(github.event.head_commit.message, 'release:')
    name: Build & Publish
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org/'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
      - name: Build & Test
        run: npm run test
      - name: Commit and push built files
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "chore: build action output"
          branch: main
          push_options: '--force'
          file_pattern: dist/*
      - name: Update `v1` tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag v1 -f
          git push origin --tag -f